# Generated by Django 2.2 on 2020-03-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('place', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='templates/journey/assets/img/')),
            ],
        ),
    ]
