# Generated by Django 2.2 on 2020-03-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0002_auto_20200320_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='desc',
            field=models.TextField(default='write here'),
        ),
    ]
