# Generated by Django 2.2 on 2020-03-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0003_memory_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='title',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
