# Generated by Django 2.2 on 2020-03-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0004_auto_20200321_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='place',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
