# Generated by Django 2.2 on 2020-03-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0005_auto_20200321_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='place',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
