# Generated by Django 2.2 on 2020-03-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0007_auto_20200321_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='desc',
            field=models.TextField(blank=True, default='write here', null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='place',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
