# Generated by Django 2.2 on 2020-03-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0008_auto_20200321_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/assets/img/'),
        ),
    ]
