# Generated by Django 2.2 on 2020-03-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0009_auto_20200321_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
