# Generated by Django 2.2 on 2020-03-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0011_auto_20200321_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jproj/media/'),
        ),
    ]
