# Generated by Django 2.2 on 2020-03-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0012_auto_20200321_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/img/'),
        ),
    ]
